trigger:
- master

pool: divyanshuagent

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: divyanshuagent
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to Azure App Service
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      name: divyanshuagent
    steps:
    - task: AzureWebApp@1
      displayName: Deploy to Azure App Service
      inputs:
        azureSubscription: 'divyanshuconnection'
        appType: 'webAppContainer'
        appName: 'divyanshu-app'
        imageName: 'divyanshureg.azurecr.io/nginx:$(tag)'